version: "3.9"

services:
  deno:
    container_name: alan-chandler
    image: "chandlera718/alan-chandler"
    restart: always
    ports:
      - "${PORT}:${PORT}"
    build:
      context: .
      dockerfile: Dockerfile
      target: base