services:
  node:
    image: "node:16-bullseye-slim"
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    ports:
      - "7001:7001"
    command: "node /usr/src/app/index.js"